apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: compute-commander

resources:
  - namespace.yaml
  - websocket-deployment.yaml
  - websocket-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - haproxy-configmap.yaml
  - haproxy-deployment.yaml
  - haproxy-service.yaml

commonLabels:
  app.kubernetes.io/part-of: compute-commander
  app.kubernetes.io/managed-by: kustomize
