apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  namespace: compute-commander
  labels:
    app: websocket-server
    app.kubernetes.io/part-of: compute-commander
spec:
  type: ClusterIP
  selector:
    app: websocket-server
  ports:
    - name: ws
      port: 8080
      targetPort: 8080
      protocol: TCP
