#!/bin/bash
# Auto-generated by cmdr — agent pane wrapper with session switch support.
# Do not edit manually; regenerated on each cmdr launch.
set -uo pipefail

SWITCH_FILE="/home/n0ko/Programs/ai/computeCommander/.computecommander/session-switch"
AGENT_CMD="claude --dangerously-skip-permissions --no-chrome --disallowedTools WebSearch WebFetch NotebookEdit"
AGENT_PID=""

# Kill the running agent process (and its children) when we detect a switch.
kill_agent() {
    if [ -n "$AGENT_PID" ] && kill -0 "$AGENT_PID" 2>/dev/null; then
        # Kill the entire process group spawned by the agent.
        kill -TERM -- -"$AGENT_PID" 2>/dev/null || kill -TERM "$AGENT_PID" 2>/dev/null
        wait "$AGENT_PID" 2>/dev/null
        AGENT_PID=""
    fi
}

# Ensure we clean up child processes on exit.
trap 'kill_agent; exit 0' EXIT INT TERM

while true; do
    if [ -f "$SWITCH_FILE" ]; then
        # A session switch was requested — kill any running agent first.
        kill_agent

        project_path=$(sed -n '1p' "$SWITCH_FILE")
        session_id=$(sed -n '2p' "$SWITCH_FILE")
        rm -f "$SWITCH_FILE"
        if [ -d "$project_path" ]; then
            cd "$project_path"
            printf '\033[36mResuming session %s in %s...\033[0m\n' "$session_id" "$project_path"
            claude --resume "$session_id" --dangerously-skip-permissions --no-chrome --disallowedTools WebSearch WebFetch NotebookEdit &
            AGENT_PID=$!
        else
            printf '\033[31mDirectory not found: %s\033[0m\n' "$project_path"
            sleep 2
            continue
        fi
    elif [ -z "$AGENT_PID" ] || ! kill -0 "$AGENT_PID" 2>/dev/null; then
        # No agent running and no switch file — start the default agent.
        if [ -n "$AGENT_PID" ]; then
            # Previous agent exited normally.
            wait "$AGENT_PID" 2>/dev/null
            AGENT_PID=""
            printf '\n\033[2mSession ended. Restarting in 2s...\033[0m\n'
            sleep 2
        fi
        eval "$AGENT_CMD" &
        AGENT_PID=$!
    fi

    # Poll for the switch file while the agent is running.
    # Check every second so the switch feels near-instant.
    sleep 1
done
