#!/bin/bash
# Auto-generated by cmdr — agent pane wrapper with session switch support.
# Do not edit manually; regenerated on each cmdr launch.
set -uo pipefail

SWITCH_DIR="/home/n0ko/.computecommander"
AGENT_CMD="claude --dangerously-skip-permissions --no-chrome --disallowedTools WebSearch WebFetch NotebookEdit"
INITIAL_DIR="/home/n0ko/Programs/ai/computeCommander"
TAB_HASH="e191dbc7"
export CMDR_TAB_HASH="$TAB_HASH"
AGENT_PID=""
LAST_TRACKED_PROJECT=""

# Per-tab CWD file: unique per tab instance (hash generated at layout time).
TAB_CWD="/tmp/cmdr-$(id -u)-${TAB_HASH}-cwd"

# Per-tab switch file: prevents race condition between multiple dashboard tabs.
SWITCH_FILE="${SWITCH_DIR}/session-switch-${TAB_HASH}"
# Global switch file: checked as fallback for external tools.
# Claimed atomically via mv to prevent race conditions between tabs.
GLOBAL_SWITCH_FILE="${SWITCH_DIR}/session-switch"
CLAIMED_SWITCH_FILE="${SWITCH_DIR}/session-switch-claimed-${TAB_HASH}"

# Write initial project dir so fp/lazygit start correctly.
echo "$INITIAL_DIR" > "$TAB_CWD"
LAST_TRACKED_PROJECT="$INITIAL_DIR"

# Set terminal title to show the current project.
printf '\033]2;CMDR:%s\007' "$INITIAL_DIR"

# Kill the running agent process and ALL its descendants.
kill_agent() {
    if [ -n "$AGENT_PID" ] && kill -0 "$AGENT_PID" 2>/dev/null; then
        # Kill child processes first (handles eval subshell + claude).
        local children
        children=$(pgrep -P "$AGENT_PID" 2>/dev/null)
        for cpid in $children; do
            kill -TERM "$cpid" 2>/dev/null
        done
        # Then kill the agent process itself.
        kill -TERM "$AGENT_PID" 2>/dev/null
        wait "$AGENT_PID" 2>/dev/null
        AGENT_PID=""
    fi
}

# Update the per-tab CWD file and tab name when the project changes.
# Also recreates the CWD file if it was deleted (e.g., by a colliding tab exit).
update_project() {
    local project="$1"
    if [ -n "$project" ] && [ -d "$project" ]; then
        if [ "$project" != "$LAST_TRACKED_PROJECT" ] || [ ! -f "$TAB_CWD" ]; then
            echo "$project" > "$TAB_CWD"
            LAST_TRACKED_PROJECT="$project"
            printf '\033]2;CMDR:%s\007' "$project"
            zellij action rename-tab "[CMDR] $(basename "$project")" 2>/dev/null || true
        fi
    fi
}

# Clean up child processes on exit. Don't delete the CWD file —
# stale files are harmless and get filtered by liveness checks.
trap 'kill_agent; exit 0' EXIT INT TERM

while true; do
    # Check per-tab switch file first (targeted).
    ACTIVE_SWITCH=""
    if [ -f "$SWITCH_FILE" ]; then
        ACTIVE_SWITCH="$SWITCH_FILE"
    elif [ -f "$GLOBAL_SWITCH_FILE" ]; then
        # Atomically claim the global switch file via rename.
        # Only one tab can successfully mv; losers see "No such file".
        if mv "$GLOBAL_SWITCH_FILE" "$CLAIMED_SWITCH_FILE" 2>/dev/null; then
            ACTIVE_SWITCH="$CLAIMED_SWITCH_FILE"
        fi
    fi

    if [ -n "$ACTIVE_SWITCH" ]; then
        # A session switch was requested — kill any running agent first.
        kill_agent

        project_path=$(sed -n '1p' "$ACTIVE_SWITCH")
        session_id=$(sed -n '2p' "$ACTIVE_SWITCH")
        rm -f "$ACTIVE_SWITCH"
        if [ -d "$project_path" ]; then
            cd "$project_path"
            # Update per-tab CWD so fp and lazygit follow the new project.
            update_project "$project_path"
            printf '\033[36mResuming session %s in %s...\033[0m\n' "$session_id" "$project_path"
            claude --resume "$session_id" --dangerously-skip-permissions --no-chrome --disallowedTools WebSearch WebFetch NotebookEdit &
            AGENT_PID=$!
        else
            printf '\033[31mDirectory not found: %s\033[0m\n' "$project_path"
            sleep 2
            continue
        fi
    elif [ -z "$AGENT_PID" ] || ! kill -0 "$AGENT_PID" 2>/dev/null; then
        # No agent running and no switch file — start the default agent.
        if [ -n "$AGENT_PID" ]; then
            # Previous agent exited normally.
            wait "$AGENT_PID" 2>/dev/null
            AGENT_PID=""
            printf '\n\033[2mSession ended. Restarting in 2s...\033[0m\n'
            sleep 2
        fi
        eval "$AGENT_CMD" &
        AGENT_PID=$!
    fi

    # Poll for the switch file while the agent is running.
    # Check every second so the switch feels near-instant.
    sleep 1
done
