#!/bin/bash
# Auto-generated by cmdr — focus-watcher restart wrapper.
# Do not edit manually; regenerated on each cmdr launch.
#
# Wraps the focus-watcher (Rust binary or bash fallback) with automatic
# restart on exit. Without this, a crashed focus-watcher leaves the CWD
# file stale, causing fp and lazygit panes to stop receiving updates.
set -uo pipefail

WATCHER_CMD="\"/home/n0ko/Programs/ai/computeCommander/plugins/focus-watcher/target/release/focus-watcher\" --tab-hash \"abc12345\" --poll-ms 250"
LOG_FILE="/tmp/cmdr-$(id -u)-focus-watcher.log"
RESTART_DELAY=3
MAX_RAPID_RESTARTS=5
RAPID_WINDOW=30

restart_count=0
window_start=$(date +%s)

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"
}

trap 'log "wrapper exiting (signal)"; exit 0' EXIT INT TERM

log "focus-watcher wrapper started"

while true; do
    now=$(date +%s)
    elapsed=$(( now - window_start ))

    # Reset the rapid-restart counter if we're outside the window.
    if [ "$elapsed" -ge "$RAPID_WINDOW" ]; then
        restart_count=0
        window_start=$now
    fi

    # If we've hit too many rapid restarts, back off longer.
    if [ "$restart_count" -ge "$MAX_RAPID_RESTARTS" ]; then
        log "too many rapid restarts ($restart_count in ${elapsed}s), backing off 30s"
        sleep 30
        restart_count=0
        window_start=$(date +%s)
    fi

    log "starting focus-watcher (restart #${restart_count})"
    eval $WATCHER_CMD
    exit_code=$?
    log "focus-watcher exited with code $exit_code"

    restart_count=$(( restart_count + 1 ))
    log "restarting in ${RESTART_DELAY}s..."
    sleep "$RESTART_DELAY"
done
