#!/bin/bash
# Auto-generated by cmdr — focus-watcher for dynamic pane CWD tracking.
# Do not edit manually; regenerated on each cmdr launch.
#
# Polls zellij for the focused pane, finds the foreground process on its
# pts device via /proc, and writes the CWD to the per-tab CWD file.
# fp-wrapper and lazygit-wrapper watch this file to follow focus.

set -uo pipefail

TAB_HASH="443c43bc"
CWD_FILE="/tmp/cmdr-$(id -u)-${TAB_HASH}-cwd"
POLL_INTERVAL="${CMDR_FOCUS_POLL:-2}"
LAST_CWD=""

# cleanup: nothing persistent to remove beyond what wrappers manage.
trap 'exit 0' EXIT INT TERM

# focused_pane_pts returns the pts device number for the focused pane,
# or empty string if it cannot be determined.
# zellij action list-clients output: CLIENT_ID ZELLIJ_PANE_ID RUNNING_COMMAND
# ZELLIJ_PANE_ID looks like "terminal_N" where N is the pts minor number.
focused_pane_pts() {
    local clients
    clients=$(zellij action list-clients 2>/dev/null) || return
    # Skip header line. Find the row for client 1 (the user's client).
    # Extract terminal_N and strip prefix to get the pts number.
    echo "$clients" | awk 'NR>1 && $1=="1" {
        pane=$2
        sub(/^terminal_/, "", pane)
        print pane
        exit
    }'
}

# fg_cwd_for_pts returns the CWD of the foreground process on /dev/pts/N.
# It scans /proc/*/stat to find a process whose tty_nr matches pts/N
# and whose pgrp equals tpgid (meaning it is in the terminal's fg group).
# Safe stat parsing strips the comm field (which may contain spaces/parens).
fg_cwd_for_pts() {
    local pts_num="$1"
    # pts tty_nr = makedev(136, pts_num) = 136*256 + pts_num
    local tty_nr=$(( 136 * 256 + pts_num ))
    local best_pid=""
    local best_cwd=""

    for stat_file in /proc/[0-9]*/stat; do
        local pid
        pid=${stat_file%/stat}
        pid=${pid##*/proc/}
        local raw
        raw=$(cat "$stat_file" 2>/dev/null) || continue
        # Strip comm (may contain spaces): remove first '(' to last ')'.
        local clean="${raw/\(*/X }"
        local rest="${raw##*\)}"
        clean="${clean}${rest}"
        # Fields after stripping: pid X state ppid pgrp session tty_nr tpgid ...
        local f_tty f_pgrp f_tpgid
        f_tty=$(echo "$clean"  | awk '{print $7}')
        f_pgrp=$(echo "$clean" | awk '{print $5}')
        f_tpgid=$(echo "$clean" | awk '{print $8}')
        [ "$f_tty" = "$tty_nr" ]   || continue
        [ "$f_pgrp" = "$f_tpgid" ] || continue
        local cwd
        cwd=$(readlink "/proc/$pid/cwd" 2>/dev/null) || continue
        [ -d "$cwd" ] || continue
        # Prefer the process with the longest (most specific) CWD.
        if [ ${#cwd} -gt ${#best_cwd} ]; then
            best_pid="$pid"
            best_cwd="$cwd"
        fi
    done

    echo "$best_cwd"
}

# Main loop: poll for focus changes and update the CWD file.
while true; do
    pts=$(focused_pane_pts)
    if [ -n "$pts" ] && [ "$pts" -ge 0 ] 2>/dev/null; then
        cwd=$(fg_cwd_for_pts "$pts")
        if [ -n "$cwd" ] && [ "$cwd" != "$LAST_CWD" ] && [ -d "$cwd" ]; then
            # Skip ~/.claude — it is the Claude config dir, not a project.
            if [ "$cwd" != "${HOME}/.claude" ]; then
                echo "$cwd" > "$CWD_FILE"
                LAST_CWD="$cwd"
            fi
        fi
    fi
    sleep "$POLL_INTERVAL"
done
