#!/bin/bash
# Auto-generated by cmdr — fp wrapper with session-switch tracking.
# Do not edit manually; regenerated on each cmdr launch.
# Uses inotifywait on a per-tab CWD file for instant, isolated updates.
set -uo pipefail

DEFAULT_DIR="${1:-/home/n0ko/Programs/ai/computeCommander}"
# $2 is the tab hash passed from the KDL layout args at launch time.
# Fall back to the compile-time hash so existing running instances stay valid.
TAB_HASH="${2:-f9539735}"
export CMDR_TAB_HASH="$TAB_HASH"
FP_PID=""
HAS_INOTIFY=false
command -v inotifywait >/dev/null 2>&1 && HAS_INOTIFY=true

# Per-tab CWD file: hash generated at layout time, shared with agent-wrapper.
CWD_FILE="/tmp/cmdr-$(id -u)-${TAB_HASH}-cwd"

start_fp() {
    local dir="${1:-$DEFAULT_DIR}"
    [ -d "$dir" ] || dir="$DEFAULT_DIR"
    # Update the pane title to reflect the current project.
    # Uses terminal escape sequence so it works from within this pane
    # regardless of which pane has focus (unlike zellij action rename-pane).
    printf '\033]2;fp: %s\007' "$(basename "$dir")"
    fp "$dir" &
    FP_PID=$!
}

kill_fp() {
    if [ -n "$FP_PID" ] && kill -0 "$FP_PID" 2>/dev/null; then
        kill "$FP_PID" 2>/dev/null
        wait "$FP_PID" 2>/dev/null
        FP_PID=""
    fi
}

trap 'kill_fp; exit 0' EXIT INT TERM

# Start with the project dir from $1 (layout argument).
CURRENT_DIR="$DEFAULT_DIR"
start_fp "$CURRENT_DIR"

# Wait for the per-tab CWD file to appear (agent-wrapper creates it).
while [ ! -f "$CWD_FILE" ]; do sleep 1; done

while true; do
    if $HAS_INOTIFY; then
        inotifywait -qq -e close_write -t 10 "$CWD_FILE" 2>/dev/null || true
    else
        sleep 2
    fi

    if [ -f "$CWD_FILE" ]; then
        NEW_DIR="$(tr -d '\n' < "$CWD_FILE" 2>/dev/null)"
        if [ -n "$NEW_DIR" ] && [ "$NEW_DIR" != "$CURRENT_DIR" ] && [ -d "$NEW_DIR" ]; then
            CURRENT_DIR="$NEW_DIR"
            kill_fp
            # start_fp updates the pane title via terminal escape sequence (printf '\033]2;...\007')
            # which works because no KDL name= attribute overrides it.
            start_fp "$CURRENT_DIR"
        fi
    fi

    # Restart fp if it died.
    if [ -n "$FP_PID" ] && ! kill -0 "$FP_PID" 2>/dev/null; then
        wait "$FP_PID" 2>/dev/null
        start_fp "$CURRENT_DIR"
    fi
done
