#!/bin/bash
# Auto-generated by cmdr — lazygit wrapper with session-switch tracking.
# Do not edit manually; regenerated on each cmdr launch.
# Uses inotifywait on a per-tab CWD file for instant, isolated updates.
set -uo pipefail

DEFAULT_DIR="${1:-/home/n0ko/Programs/ai/computeCommander}"
# $2 is the tab hash passed from the KDL layout args at launch time.
# Fall back to the compile-time hash so existing running instances stay valid.
TAB_HASH="${2:-443c43bc}"
export CMDR_TAB_HASH="$TAB_HASH"
LG_PID=""
HAS_INOTIFY=false
command -v inotifywait >/dev/null 2>&1 && HAS_INOTIFY=true

# Per-tab CWD file: hash generated at layout time, shared with agent-wrapper.
CWD_FILE="/tmp/cmdr-$(id -u)-${TAB_HASH}-cwd"

start_lg() {
    local dir="${1:-$DEFAULT_DIR}"
    [ -d "$dir" ] || dir="$DEFAULT_DIR"
    if [ -d "$dir/.git" ] || git -C "$dir" rev-parse --git-dir >/dev/null 2>&1; then
        lazygit -p "$dir" &
        LG_PID=$!
    else
        echo "Not a git repository: $dir"
        LG_PID=""
    fi
}

kill_lg() {
    if [ -n "$LG_PID" ] && kill -0 "$LG_PID" 2>/dev/null; then
        kill "$LG_PID" 2>/dev/null
        wait "$LG_PID" 2>/dev/null
        LG_PID=""
    fi
}

trap 'kill_lg; exit 0' EXIT INT TERM

# Start with the project dir from $1 (layout argument).
CURRENT_DIR="$DEFAULT_DIR"
start_lg "$CURRENT_DIR"

# Wait for the per-tab CWD file to appear (agent-wrapper creates it).
while [ ! -f "$CWD_FILE" ]; do sleep 1; done

while true; do
    if $HAS_INOTIFY; then
        inotifywait -qq -e close_write -t 10 "$CWD_FILE" 2>/dev/null || true
    else
        sleep 2
    fi

    if [ -f "$CWD_FILE" ]; then
        NEW_DIR="$(tr -d '\n' < "$CWD_FILE" 2>/dev/null)"
        if [ -n "$NEW_DIR" ] && [ "$NEW_DIR" != "$CURRENT_DIR" ] && [ -d "$NEW_DIR" ]; then
            CURRENT_DIR="$NEW_DIR"
            kill_lg
            start_lg "$CURRENT_DIR"
        fi
    fi

    if [ -n "$LG_PID" ] && ! kill -0 "$LG_PID" 2>/dev/null; then
        wait "$LG_PID" 2>/dev/null
        start_lg "$CURRENT_DIR"
    fi
done
