// Code generated by bridge/types/generator.go -- DO NOT EDIT.
// Source: bridge/bridge.go

/** HookManifest is the top-level manifest that lists all hook bindings. */
export interface HookManifest {
  version: number;
  hooks: HookBinding[];
}

/** HookBinding maps a named Go hook to the events it handles across runtimes. */
export interface HookBinding {
  name: string;
  goPackage: string;
  piEvents: string[];
  claudeEvents: string[];
  matcher?: string;
  inputSchema?: string;
  outputSchema?: string;
}

/** BridgeRequest is the JSON envelope sent to hook-bridge on stdin. */
export interface BridgeRequest {
  hook: string;
  event: string;
  payload: unknown;
  sessionId?: string;
}

/** BridgeResponse is the JSON envelope written to stdout by hook-bridge. */
export interface BridgeResponse {
  success: boolean;
  output?: unknown;
  error?: string;
  context?: string;
}
