// Package types generates TypeScript interface definitions from Go struct types
// annotated with the "bridge:export" comment marker.
//
// Usage:
//
//	//go:generate go run ./cmd/hook-bridge --generate
package types

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

// goToTS maps Go type names to their TypeScript equivalents.
var goToTS = map[string]string{
	"string":          "string",
	"int":             "number",
	"int8":            "number",
	"int16":           "number",
	"int32":           "number",
	"int64":           "number",
	"uint":            "number",
	"uint8":           "number",
	"uint16":          "number",
	"uint32":          "number",
	"uint64":          "number",
	"float32":         "number",
	"float64":         "number",
	"bool":            "boolean",
	"json.RawMessage": "unknown",
	"RawMessage":      "unknown",
}

// StructInfo holds the parsed information for a single exported struct.
type StructInfo struct {
	Name   string
	Fields []FieldInfo
	Doc    string
}

// FieldInfo holds the parsed information for a single struct field.
type FieldInfo struct {
	Name     string
	TSType   string
	Optional bool
	JSONName string
	Doc      string
}

// ParseFile parses a Go source file and returns all structs tagged with
// the "bridge:export" comment.
func ParseFile(filePath string) ([]StructInfo, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", filePath, err)
	}

	var structs []StructInfo

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// Check for bridge:export marker in the comment group.
			if !hasBridgeExport(genDecl.Doc) && !hasBridgeExport(typeSpec.Doc) {
				continue
			}

			info := StructInfo{
				Name: typeSpec.Name.Name,
				Doc:  extractDoc(genDecl.Doc),
			}

			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue // embedded field
				}

				fi := FieldInfo{
					Name:   field.Names[0].Name,
					TSType: resolveType(field.Type),
					Doc:    extractDoc(field.Doc),
				}

				// Parse JSON tag for name and omitempty.
				if field.Tag != nil {
					jsonName, omit := parseJSONTag(field.Tag.Value)
					if jsonName != "" {
						fi.JSONName = jsonName
					}
					fi.Optional = omit
				}

				// Pointer types are always optional.
				if _, ok := field.Type.(*ast.StarExpr); ok {
					fi.Optional = true
				}

				if fi.JSONName == "" {
					fi.JSONName = fi.Name
				}

				// Skip fields tagged with json:"-".
				if fi.JSONName == "-" {
					continue
				}

				info.Fields = append(info.Fields, fi)
			}

			structs = append(structs, info)
		}
	}

	return structs, nil
}

// GenerateTypeScript produces TypeScript interface declarations from the
// given struct infos.
func GenerateTypeScript(structs []StructInfo) string {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by bridge/types/generator.go -- DO NOT EDIT.\n")
	buf.WriteString("// Source: bridge/bridge.go\n\n")

	for i, s := range structs {
		if s.Doc != "" {
			buf.WriteString("/** " + s.Doc + " */\n")
		}
		buf.WriteString("export interface " + s.Name + " {\n")
		for _, f := range s.Fields {
			if f.Doc != "" {
				buf.WriteString("  /** " + f.Doc + " */\n")
			}
			opt := ""
			if f.Optional {
				opt = "?"
			}
			buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.JSONName, opt, f.TSType))
		}
		buf.WriteString("}\n")
		if i < len(structs)-1 {
			buf.WriteString("\n")
		}
	}

	return buf.String()
}

// GenerateToFile parses Go source files and writes TypeScript interfaces
// to the output path.
func GenerateToFile(inputPaths []string, outputPath string) error {
	var allStructs []StructInfo

	for _, p := range inputPaths {
		structs, err := ParseFile(p)
		if err != nil {
			return err
		}
		allStructs = append(allStructs, structs...)
	}

	if len(allStructs) == 0 {
		return fmt.Errorf("no structs with bridge:export marker found in %v", inputPaths)
	}

	ts := GenerateTypeScript(allStructs)
	if err := os.WriteFile(outputPath, []byte(ts), 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	return nil
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// hasBridgeExport checks whether a comment group contains a standalone
// "bridge:export" directive (the comment text must be exactly "// bridge:export"
// or start with "// bridge:export " to avoid false positives from prose).
func hasBridgeExport(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == "bridge:export" || strings.HasPrefix(text, "bridge:export ") {
			return true
		}
	}
	return false
}

// resolveType converts a Go AST type expression to a TypeScript type string.
func resolveType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if ts, ok := goToTS[t.Name]; ok {
			return ts
		}
		return t.Name

	case *ast.SelectorExpr:
		full := fmt.Sprintf("%s.%s", t.X, t.Sel.Name)
		if ts, ok := goToTS[full]; ok {
			return ts
		}
		return t.Sel.Name

	case *ast.ArrayType:
		elem := resolveType(t.Elt)
		return elem + "[]"

	case *ast.StarExpr:
		inner := resolveType(t.X)
		return inner + " | undefined"

	case *ast.MapType:
		key := resolveType(t.Key)
		val := resolveType(t.Value)
		return fmt.Sprintf("Record<%s, %s>", key, val)

	case *ast.InterfaceType:
		return "unknown"

	default:
		return "unknown"
	}
}

// parseJSONTag extracts the field name and omitempty flag from a struct tag.
func parseJSONTag(tagValue string) (name string, omitempty bool) {
	tag := strings.Trim(tagValue, "`")
	for _, part := range strings.Split(tag, " ") {
		part = strings.TrimSpace(part)
		if !strings.HasPrefix(part, `json:"`) {
			continue
		}
		val := strings.TrimPrefix(part, `json:"`)
		val = strings.TrimSuffix(val, `"`)
		parts := strings.Split(val, ",")
		name = parts[0]
		for _, p := range parts[1:] {
			if p == "omitempty" {
				omitempty = true
			}
		}
		return
	}
	return "", false
}

// extractDoc pulls the text from a comment group, stripping comment markers.
func extractDoc(cg *ast.CommentGroup) string {
	if cg == nil {
		return ""
	}
	var parts []string
	for _, c := range cg.List {
		text := c.Text
		text = strings.TrimPrefix(text, "//")
		text = strings.TrimPrefix(text, "/*")
		text = strings.TrimSuffix(text, "*/")
		text = strings.TrimSpace(text)
		if text != "" && !strings.HasPrefix(text, "bridge:") {
			parts = append(parts, text)
		}
	}
	return strings.Join(parts, " ")
}
