package linkedin

import (
	"bytes"
	"fmt"
	"html"
	"strings"
	"text/template"
)

// emailTemplate is the HTML email template for post review.
var emailTemplate = template.Must(template.New("email").Parse(`<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333;">

<h2 style="color: #0A66C2;">LinkedIn Post Draft</h2>

<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
<tr><td style="padding: 4px 12px 4px 0; font-weight: bold; color: #666;">Topic:</td><td>{{.Topic}}</td></tr>
<tr><td style="padding: 4px 12px 4px 0; font-weight: bold; color: #666;">Source Project:</td><td>{{.SourceProject}}</td></tr>
<tr><td style="padding: 4px 12px 4px 0; font-weight: bold; color: #666;">Generated:</td><td>{{.CreatedAt}}</td></tr>
<tr><td style="padding: 4px 12px 4px 0; font-weight: bold; color: #666;">Target:</td><td>{{.Target}}</td></tr>
</table>

<hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;"/>

<h3 style="color: #333;">Post Content</h3>
<div style="background: #f5f5f5; padding: 16px; border-radius: 8px; font-family: sans-serif; line-height: 1.6;">
{{.ContentHTML}}
</div>

<hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;"/>

{{if .DiagramDesc}}
<h3 style="color: #333;">Visual Asset Description</h3>
<p style="background: #fff3cd; padding: 12px; border-radius: 8px; border-left: 4px solid #ffc107;">{{.DiagramDesc}}</p>
<p style="color: #666; font-style: italic;">Create this diagram using draw.io, Excalidraw, or similar tool.</p>

<hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;"/>
{{end}}

<h3 style="color: #333;">Plain Text (Copy-Paste to LinkedIn)</h3>
<pre style="background: #1a1a1a; color: #e0e0e0; padding: 16px; border-radius: 8px; white-space: pre-wrap; word-wrap: break-word; font-size: 13px; line-height: 1.5;">{{.ContentPlain}}</pre>

<hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;"/>

<div style="background: #e8f4fd; padding: 16px; border-radius: 8px;">
<p style="margin: 0 0 8px; font-weight: bold; color: #0A66C2;">Actions:</p>
<ul style="margin: 0; padding-left: 20px; color: #333;">
<li>Approve: <code style="background: #f0f0f0; padding: 2px 6px; border-radius: 3px;">cc linkedin approve {{.PostID}}</code></li>
<li>Reject: <code style="background: #f0f0f0; padding: 2px 6px; border-radius: 3px;">cc linkedin reject {{.PostID}}</code></li>
<li>Edit: Reply to this email with changes</li>
</ul>
</div>

<p style="color: #999; font-size: 12px; margin-top: 20px; text-align: center;">
Generated by ComputeCommander LinkedIn Post Generator
</p>

</body>
</html>`))

// emailData is the template data for rendering review emails.
type emailData struct {
	Topic         string
	SourceProject string
	CreatedAt     string
	Target        string
	ContentHTML   string
	ContentPlain  string
	DiagramDesc   string
	PostID        int64
}

// Renderer formats posts into HTML email and plain text for review.
type Renderer struct{}

// NewRenderer creates a new Renderer.
func NewRenderer() *Renderer {
	return &Renderer{}
}

// RenderEmail produces the full HTML email body for post review.
func (r *Renderer) RenderEmail(p *Post) (string, error) {
	data := emailData{
		Topic:         p.Topic,
		SourceProject: p.SourceProject,
		CreatedAt:     p.CreatedAt.Format("2006-01-02 15:04 UTC"),
		Target:        string(p.Target),
		ContentHTML:   contentToHTML(p.Content),
		ContentPlain:  p.Content,
		DiagramDesc:   p.DiagramDesc,
		PostID:        p.ID,
	}

	var buf bytes.Buffer
	if err := emailTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render email template: %w", err)
	}

	return buf.String(), nil
}

// RenderSubject generates the email subject line.
func (r *Renderer) RenderSubject(p *Post) string {
	return fmt.Sprintf("[LinkedIn Draft] %s -- Ready for Review", p.Title)
}

// RenderPlainText formats the post content for direct LinkedIn copy-paste.
func (r *Renderer) RenderPlainText(p *Post) string {
	return p.Content
}

// contentToHTML converts plain text post content to basic HTML with paragraph breaks.
func contentToHTML(content string) string {
	escaped := html.EscapeString(content)

	// Convert double newlines to paragraph breaks.
	paragraphs := strings.Split(escaped, "\n\n")
	var htmlParts []string
	for _, para := range paragraphs {
		para = strings.TrimSpace(para)
		if para == "" {
			continue
		}
		// Convert single newlines to <br>.
		para = strings.ReplaceAll(para, "\n", "<br>")
		htmlParts = append(htmlParts, "<p>"+para+"</p>")
	}

	return strings.Join(htmlParts, "\n")
}
